### ISSUE TITLE
참신한 새로운 기능에 대한 아이디어 필요

### ISSUE THREAD

**Issue by hancheng1995** [skkuse/2019spring_41class_team4#1]
조교님의 의견대로 시간이 남으면 참신한 기능을 하나 추가할려고하는데 좋은 아이디어 있으면 말해주세요

**Comment by jyfregramer** [comment]
운영자가 입력한 시간에 제일 처음 접속하는 사람에게 할인 쿠폰을 제공하는 시스템은 어떨까요?
