### ISSUE TITLE
foodform 글 작성시 로그인한 user로 저장

### ISSUE THREAD

**Issue by ha012345** [skkuse/2019spring_41class_team4#10]
foodform에 글을 작성할 때 로그인한 user의 이름 정보로 food 데이터베이스에 자동으로 저장하도록 한다

**Comment by hancheng1995** [comment]
유저의 이름이 저장되는것을 확인했습니다.

**Comment by ha012345** [comment]
24d55945970be4c6baf31783aaaca1ea82fd41bb
