### ISSUE TITLE
이미지 파일 업로드 방법 찾기

### ISSUE THREAD

**Issue by jyfregramer** [skkuse/2019spring_41class_team4#5]
Image Field

**Comment by ChesterLu** [comment]
https://github.com/divio/django-filer

**Comment by jyfregramer** [comment]
https://wsvincent.com/django-image-uploads/

**Comment by ha012345** [comment]
#5 모델 food, board에 이미지필드 추가하고 글 작성하는 곳에 이미지 업로드 기능 구현 및 글 클릭시에  이미지 불러오기, foodlist에 이미지 미리보기 구현

**Comment by ha012345** [comment]
c6e1bc6aa35434004069175513bc46f040b87a8b
