### ISSUE TITLE
community 글 작성

### ISSUE THREAD

**Issue by ha012345** [skkuse/2019spring_41class_team4#9]
community 에서 write post 버튼을 클릭하면 글을 작성할 수 있는 페이지가 뜨고 그 페이지에서 내용 작성 후에 submit버튼을 클릭하면 community 메인 페이지로 돌아가면서 데이터베이스에 글이 저장되도록 한다

**Comment by hancheng1995** [comment]
글작성 기능 작동 확인

**Comment by ha012345** [comment]
82af7e8d7ac1845fa9d2bcd1890358dcba315c2a
